name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [windows, linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Build for ${{ matrix.goos }}_amd64
        run: |
          if [ "${{ matrix.goos }}" = "windows" ]; then EXT=".exe"; else EXT=""; fi
          GOOS=${{ matrix.goos }} GOARCH=amd64 go build -ldflags="-s -w" -trimpath -o build/panel_storage_${{ github.ref_name }}_${{ matrix.goos }}_amd64$EXT

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: panel_storage_${{ github.ref_name }}_${{ matrix.goos }}_amd64
          path: ./build/panel_storage_${{ github.ref_name }}_${{ matrix.goos }}_amd64*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./build/**
          name: "Release ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
